Repository atlp-rwanda/rca-barefoot-team6-bn, pull requests merged in 2023-03, with the labels that each got.

#9 Ch configured eslint 184638361
  .eslintrc.js
  src/index.js
Labels: enhancement, Need review., chore

#6 chore(docker): create Dockerfile for node
  .dockerignore
  Dockerfile
  docker-compose.yml
  docker/dev/.gitkeep
Labels: Need review., chore

#10 Chore gh actions 184638363
  .DS_Store
  .github/workflows/build-ci.yml
  .github/workflows/test-ci.yml
  README.md
  package.json
  yarn.lock
Labels: documentation, Need review., chore

#8 #184638360 setup PostgreSQL and Sequelize
  .sequelizerc
  package-lock.json
  package.json
  src/config/.gitkeep
  src/database/.gitkeep
  src/database/config/config.js
  src/database/migrations/20230311231119-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20230311232716-sample-users.js
Labels: Need review., chore, database

#13 #184638363 Pull Request template & Improve test and build workflows
  .github/pull_request_template.md
  .github/workflows/build-ci.yml
  .github/workflows/test-ci.yml
  package.json
Labels: enhancement, Need review., chore

#14 #184639260 env setup and database variables
  .env.example
  package-lock.json
  package.json
  src/app.js
  src/database/config/config.js
  src/database/migrations/20230311231119-create-user.js
  src/database/models/index.js
Labels: Need review., chore

#22 feat: added swagger documentation with OpenAPI
  package-lock.json
  package.json
  src/app.js
  src/swagger/hello/index.js
  src/swagger/index.js
  src/swagger/responses.js
Labels: documentation, Need review.

#30 ft:User Registration and Email Verification
  .env.example
  package.json
  src/controllers/userController.js
  src/database/models/user.js
  src/middlewares/authMiddleware.js
  src/routes/userRoute.js
  src/swagger/index.js
  src/swagger/user/index.js
  src/utils/emailVerificationToken.js
  src/utils/sendEmail.js
Labels: Need review.

#20 Ft:lougout 184638376
  .env.example
  .gitignore
  Dockerfile
  docker-compose.yml
  nodemon.json
  package-lock.json
  package.json
  src/app.js
  src/controllers/userController.js
  src/database/config/config.js
  src/database/config/db.js
  src/database/models/index.js
  src/database/models/token.js
  src/database/models/user.js
  src/middlewares/authMiddleware.js
  src/routes/userRoute.js
  src/swagger/index.js
  src/swagger/user/index.js
  src/utils/sendEmailAndToken.js
  swagger/swagger.json
  swaggiffy.config.json
Labels: Need review.

#18 #184638373 user login
  src/controllers/userController.js
  src/routes/userRoute.js
  swagger/swagger.json
  swaggiffy.config.json
Labels: enhancement, Need review.

#31 feat: login with social works fine
  .env.example
  src/app.js
  src/controllers/authController.js
  src/database/migrations/20230311231119-create-user.js
  src/database/models/user.js
  src/routes/index.js
  src/routes/userRoute.js
  src/services/userService.js
  src/swagger/auth/index.js
  src/swagger/index.js
Labels: enhancement, Need review., Rebase needed.
